// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Sergio Virahonda",
            "url": "https://www.linkedin.com/in/sergiovirahonda/",
            "email": "svirahonda@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v0/echo/": {
            "post": {
                "description": "Creates an Echo resource and returns it echoed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "echo"
                ],
                "summary": "Creates an Echo resource.",
                "parameters": [
                    {
                        "description": "Echo object",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EchoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.EchoResponseFromRequest"
                        }
                    }
                }
            }
        },
        "/v0/whats-echoed/": {
            "get": {
                "description": "Gets all Echo resources.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "echo"
                ],
                "summary": "Gets all Echo resources.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EchoResponses"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.EchoRequest": {
            "type": "object",
            "required": [
                "echo-me"
            ],
            "properties": {
                "echo-me": {
                    "type": "string"
                }
            }
        },
        "models.EchoResponse": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "models.EchoResponseFromRequest": {
            "type": "object",
            "properties": {
                "echo-you": {
                    "type": "string"
                }
            }
        },
        "models.EchoResponses": {
            "type": "object",
            "properties": {
                "whats-echoed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.EchoResponse"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v0",
	Schemes:          []string{},
	Title:            "Echo API",
	Description:      "This is a sample and very simple Echo API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
