basePath: /v0
definitions:
  models.EchoRequest:
    properties:
      echo-me:
        type: string
    required:
    - echo-me
    type: object
  models.EchoResponse:
    properties:
      time:
        type: string
      value:
        type: string
    type: object
  models.EchoResponseFromRequest:
    properties:
      echo-you:
        type: string
    type: object
  models.EchoResponses:
    properties:
      whats-echoed:
        items:
          $ref: '#/definitions/models.EchoResponse'
        type: array
    type: object
host: localhost:8080
info:
  contact:
    email: svirahonda@gmail.com
    name: Sergio Virahonda
    url: https://www.linkedin.com/in/sergiovirahonda/
  description: This is a sample and very simple Echo API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Echo API
  version: "1.0"
paths:
  /v0/echo/:
    post:
      consumes:
      - application/json
      description: Creates an Echo resource and returns it echoed.
      parameters:
      - description: Echo object
        in: body
        name: resource
        required: true
        schema:
          $ref: '#/definitions/models.EchoRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.EchoResponseFromRequest'
      summary: Creates an Echo resource.
      tags:
      - echo
  /v0/whats-echoed/:
    get:
      description: Gets all Echo resources.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.EchoResponses'
      summary: Gets all Echo resources.
      tags:
      - echo
swagger: "2.0"
